
# ディメンション生成のチェック
  data modify storage iemp: DimensionGenerated set value 0b
  execute store success storage iemp: DimensionGenerated byte 1 in iemp: run help help .
  execute unless data storage iemp: {DimensionGenerated:1b} run tellraw @a {"text":"==============================\nディメンションの生成を確認できませんでした。\n生成にはワールドの再読み込みが必要です。\n==============================","color":"#ff0000"}

# 追加ディメンションに対してforceloadと固定UUIDのmarkerの設置を行う
  execute if data storage iemp: {DimensionGenerated:1b} in iemp: run forceload add -1 -1 1 1
  execute if data storage iemp: {DimensionGenerated:1b} in iemp: run summon marker 0.0 0.0 0.0 {UUID:[I;20200628,1847293066,-2081736452,20200628]}


scoreboard objectives add iemp_value dummy

scoreboard objectives add 2 dummy
scoreboard players set #global 2 2


scoreboard objectives add -1 dummy
scoreboard players set #global -1 -1

scoreboard objectives add 100 dummy
scoreboard players set #global 100 100

scoreboard objectives add 1000 dummy
scoreboard players set #global 1000 1000

scoreboard objectives add 10000 dummy
scoreboard players set #global 10000 10000
